// Mocks generated by Mockito 5.4.6 from annotations
// in aldeewan_mobile/test/presentation/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aldeewan_mobile/data/services/balance_calculator_service.dart'
    as _i7;
import 'package:aldeewan_mobile/domain/entities/person.dart' as _i4;
import 'package:aldeewan_mobile/domain/entities/transaction.dart' as _i6;
import 'package:aldeewan_mobile/domain/repositories/person_repository.dart'
    as _i2;
import 'package:aldeewan_mobile/domain/repositories/transaction_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i2.PersonRepository {
  MockPersonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Person>> watchPeople() =>
      (super.noSuchMethod(
            Invocation.method(#watchPeople, []),
            returnValue: _i3.Stream<List<_i4.Person>>.empty(),
          )
          as _i3.Stream<List<_i4.Person>>);

  @override
  _i3.Future<List<_i4.Person>> getPeople() =>
      (super.noSuchMethod(
            Invocation.method(#getPeople, []),
            returnValue: _i3.Future<List<_i4.Person>>.value(<_i4.Person>[]),
          )
          as _i3.Future<List<_i4.Person>>);

  @override
  _i3.Future<_i4.Person?> getPerson(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPerson, [id]),
            returnValue: _i3.Future<_i4.Person?>.value(),
          )
          as _i3.Future<_i4.Person?>);

  @override
  _i3.Future<void> addPerson(_i4.Person? person) =>
      (super.noSuchMethod(
            Invocation.method(#addPerson, [person]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updatePerson(_i4.Person? person) =>
      (super.noSuchMethod(
            Invocation.method(#updatePerson, [person]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePerson(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePerson, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i5.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i6.Transaction>> watchTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#watchTransactions, []),
            returnValue: _i3.Stream<List<_i6.Transaction>>.empty(),
          )
          as _i3.Stream<List<_i6.Transaction>>);

  @override
  _i3.Future<List<_i6.Transaction>> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: _i3.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i3.Future<List<_i6.Transaction>>);

  @override
  _i3.Future<List<_i6.Transaction>> getTransactionsByPerson(String? personId) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByPerson, [personId]),
            returnValue: _i3.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i3.Future<List<_i6.Transaction>>);

  @override
  _i3.Future<List<_i6.Transaction>> getTransactionsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByDateRange, [start, end]),
            returnValue: _i3.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i3.Future<List<_i6.Transaction>>);

  @override
  _i3.Future<void> addTransaction(_i6.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#addTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTransaction(_i6.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTransaction(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [BalanceCalculatorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBalanceCalculatorService extends _i1.Mock
    implements _i7.BalanceCalculatorService {
  MockBalanceCalculatorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, double>> calculate(
    List<_i4.Person>? persons,
    List<_i6.Transaction>? transactions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculate, [persons, transactions]),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);
}
